//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapperDemo.SQLScripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class sql_server_scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sql_server_scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DapperDemo.SQLScripts.sql_server_scripts", typeof(sql_server_scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Companies (Name, Address, City, State, PostalCode) 
        ///VALUES(@Name, @Address, @City, @State, @PostalCode);
        ///SELECT CAST(SCOPE_IDENTITY() as int);.
        /// </summary>
        public static string companies_add {
            get {
                return ResourceManager.GetString("companies_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM Companies 
        ///WHERE CompanyId = @CompanyId.
        /// </summary>
        public static string companies_find {
            get {
                return ResourceManager.GetString("companies_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM Companies.
        /// </summary>
        public static string companies_get_all {
            get {
                return ResourceManager.GetString("companies_get_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE 
        ///FROM Companies 
        ///WHERE CompanyId = @Id.
        /// </summary>
        public static string companies_remove {
            get {
                return ResourceManager.GetString("companies_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Companies 
        ///SET Name = @Name, 
        ///Address = @Address, 
        ///City = @City, 
        ///State = @State, 
        ///PostalCode = @PostalCode 
        ///WHERE CompanyId = @CompanyId.
        /// </summary>
        public static string companies_update {
            get {
                return ResourceManager.GetString("companies_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Employees (Name, Title, Email, Phone, CompanyId) 
        ///VALUES(@Name, @Title, @Email, @Phone, @CompanyId);
        ///SELECT CAST(SCOPE_IDENTITY() as int);.
        /// </summary>
        public static string employees_add {
            get {
                return ResourceManager.GetString("employees_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM Employees 
        ///WHERE EmployeeId = @Id.
        /// </summary>
        public static string employees_find {
            get {
                return ResourceManager.GetString("employees_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM Employees.
        /// </summary>
        public static string employees_get_all {
            get {
                return ResourceManager.GetString("employees_get_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM Employees 
        ///WHERE EmployeeId = @Id.
        /// </summary>
        public static string employees_remove {
            get {
                return ResourceManager.GetString("employees_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Employees 
        ///SET Name = @Name, 
        ///Title = @Title, 
        ///Email = @Email, 
        ///Phone = @Phone, 
        ///CompanyId = @CompanyId 
        ///WHERE EmployeeId = @EmployeeId.
        /// </summary>
        public static string employees_update {
            get {
                return ResourceManager.GetString("employees_update", resourceCulture);
            }
        }
    }
}
